version: '3.3'

services:

  service:
    image: pipdevs/pip-services-invitations-node:latest
    links:
      - roles
      - msgdistribution
    #   - mongo
    #   - couchbase
    environment:
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
      - ROLES_SERVICE_HOST=roles
      - ROLES_SERVICE_PORT=8080
      - MESSAGE_DISTRIBUTION_SERVICE_HOST=roles
      - MESSAGE_DISTRIBUTION_SERVICE_PORT=8080
      # - MONGO_ENABLED=true
      # - MONGO_SERVICE_HOST=mongo
      # - MONGO_SERVICE_PORT=27017
      # - MONGO_DB=test
      # - COUCHBASE_SERVICE_HOST=couchbase
      # - COUCHBASE_SERVICE_PORT=8091
      # - COUCHBASE_USER=Administrator
      # - COUCHBASE_PASS=password
    ports:
      - "8080:8080"
      - "8090:8090"

  roles:
    image: pipdevs/pip-services-roles-node:latest
    #links:
      # - mongo
      # - couchbase
    environment:
      # - MONGO_SERVICE_URI=
      # - MONGO_SERVICE_HOST=mongo
      # - MONGO_SERVICE_PORT=27017
      # - MONGO_DB=app
      # - COUCHBASE_SERVICE_URI=
      # - COUCHBASE_SERVICE_HOST=couchbase
      # - COUCHBASE_SERVICE_PORT=8091
      # - COUCHBASE_USER=Administrator
      # - COUCHBASE_PASS=password
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true

  msgdistribution:
    image: pipdevs/pip-services-msgdistribution-node:latest
    links:
      - email
    environment:
      - EMAIL_SERVICE_HOST=email
      - EMAIL_SERVICE_PORT=8080
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true

  email:
    image: pipdevs/pip-services-email-node:latest
    environment:
      - EMAIL_DISABLED=true
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true

  # mongo:
  #   image: mongo:latest

  # couchbase:
  #   image: couchbase/server-sandbox:5.5.1
